command:
  - "python"
  - "driver.py"

env:
  - name: "MCP_SECRET_SCOPE"
    value: "database"
  - name: "MCP_SECRET_KEY"
    value: "mcp-server-url"
  - name: "MODEL_ENDPOINT"
    value: "databricks-meta-llama-3-3-70b-instruct"